"""add booking status and cancelled_at

Revision ID: 27b18158c61c
Revises: f10289023db9
Create Date: 2026-10-06 12:47:43.112674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b18158c61c'
down_revision: Union[str, Sequence[str], None] = 'f10289023db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # add_column doesn't create a new enum type on Postgres, so create it first.
    sa.Enum('confirmed', 'cancelled', name='booking_status').create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('status', sa.Enum('confirmed', 'cancelled', name='booking_status'), server_default='confirmed', nullable=False))
    op.add_column('bookings', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'cancelled_at')
    op.drop_column('bookings', 'status')
    # ### end Alembic commands ###
    sa.Enum(name='booking_status').drop(op.get_bind())
