"""create verifications table

Revision ID: 3e0881cb5449
Revises: 1ddce971d0d8
Create Date: 2026-10-04 01:14:19.913771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e0881cb5449'
down_revision: Union[str, Sequence[str], None] = '1ddce971d0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('corroborated_count', sa.Integer(), nullable=False),
    sa.Column('self_reported_count', sa.Integer(), nullable=False),
    sa.Column('documented_only_count', sa.Integer(), nullable=False),
    sa.Column('total_claimed_count', sa.Integer(), nullable=False),
    sa.Column('document_quality_weight', sa.Float(), nullable=False),
    sa.Column('document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_provider_id'), 'verifications', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_provider_id'), table_name='verifications')
    op.drop_table('verifications')
    # ### end Alembic commands ###
