"""add llm metrics to verifications

Revision ID: ec3cce2f3556
Revises: 3e0881cb5449
Create Date: 2026-10-04 01:36:21.786560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3cce2f3556'
down_revision: Union[str, Sequence[str], None] = '3e0881cb5449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('llm_model', sa.String(length=64), nullable=True))
    op.add_column('verifications', sa.Column('llm_latency_ms', sa.Integer(), nullable=True))
    op.add_column('verifications', sa.Column('llm_prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('verifications', sa.Column('llm_output_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifications', 'llm_output_tokens')
    op.drop_column('verifications', 'llm_prompt_tokens')
    op.drop_column('verifications', 'llm_latency_ms')
    op.drop_column('verifications', 'llm_model')
    # ### end Alembic commands ###
